import ApiError from "../../../../utils/ApiError.js";
import invoiceRepository from "../repositories/invoice.repository.js";
import customerRepository from "../../../parties/customers/repositories/customer.repository.js";
import branchRepository from "../../../organization/branches/repositories/branch.repository.js";
import financialPeriodRepository from "../../../finance/financial-periods/repositories/financialPeriod.repository.js";
import Batch from "../../../catalog/products/models/batch.model.js";
import ProductFacility from "../../../catalog/products/models/productFacility.model.js";
import gstLedgerRepository from "../../../finance/gst-ledger/repositories/gstLedger.repository.js";
import Company from "../../../organization/companies/models/company.model.js";
import journalVoucherService from "../../../finance/journal-vouchers/services/journalVoucher.service.js";
import accountRepository from "../../../finance/chart-of-accounts/repositories/account.repository.js";
import cashTransactionService from "../../../finance/treasury/cash-management/cash-transactions/services/cashTransaction.service.js";
import CashAccount from "../../../finance/treasury/cash-management/cash-accounts/models/cashAccount.model.js";
import bankTransactionService from "../../../finance/treasury/bank-management/bank-transactions/services/bankTransaction.service.js";
import BankAccount from "../../../finance/treasury/bank-management/bank-accounts/models/bankAccount.model.js";

const recordCustomerSale = async (customerId, saleData, companyId, workspaceId, user = null) => {
  const customer = await customerRepository.findCustomerById(customerId, companyId, workspaceId);

  if (!customer) {
    throw new ApiError(404, "Customer not found");
  }

  let resolvedBranchId = saleData.branchId || null;
  let branchCode = "BR01";
  if (!resolvedBranchId) {
    try {
      const activeBranches = await branchRepository.getCompanyBranches(companyId);
      if (Array.isArray(activeBranches) && activeBranches.length > 0) {
        resolvedBranchId = activeBranches[0]._id;
        branchCode = activeBranches[0].branchCode || branchCode;
      }
    } catch (bErr) {
      // Fallback
    }
  } else {
    try {
      const branchDoc = await branchRepository.findBranchById(resolvedBranchId);
      if (branchDoc && branchDoc.branchCode) {
        branchCode = branchDoc.branchCode;
      }
    } catch (bErr) {
      // Fallback
    }
  }

  const periods = await financialPeriodRepository.getPeriods(workspaceId, companyId, { isCurrent: true, all: true });
  let period = periods.periods && periods.periods[0];
  const financialPeriodId = period ? period._id : null;

  // Calculate Financial Year string
  let fyString;
  if (period && period.startDate && period.endDate) {
    const startYear = new Date(period.startDate).getFullYear();
    const endYear = new Date(period.endDate).getFullYear();
    fyString = `${startYear.toString().slice(-2)}${endYear.toString().slice(-2)}`;
  } else {
    const saleDate = saleData.date ? new Date(saleData.date) : new Date();
    const month = saleDate.getMonth(); // 0-11
    const year = saleDate.getFullYear();
    let startYear, endYear;
    if (month >= 3) { // April to Dec
      startYear = year;
      endYear = year + 1;
    } else { // Jan to March
      startYear = year - 1;
      endYear = year;
    }
    fyString = `${startYear.toString().slice(-2)}${endYear.toString().slice(-2)}`;
  }

  let sequenceNo = 1;
  const invoicePrefix = `${branchCode}-${fyString}-`;

  try {
    const lastInvoice = await invoiceRepository.getLatestInvoiceByPrefix(
      companyId,
      workspaceId,
      invoicePrefix
    );
    if (lastInvoice && lastInvoice.invoiceNo) {
      const parts = lastInvoice.invoiceNo.split('-');
      if (parts.length >= 3) {
        const lastSeq = parseInt(parts[2], 10);
        if (!isNaN(lastSeq)) {
          sequenceNo = lastSeq + 1;
        }
      }
    }
  } catch (err) {
    console.error("Error generating invoice sequence:", err);
  }

  const generatedInvoiceNo = `${invoicePrefix}${sequenceNo.toString().padStart(4, '0')}`;

  const isAutoGenerated = saleData.invoiceNo && (saleData.invoiceNo.startsWith("RET-INV") || saleData.invoiceNo.startsWith("TAX-INV"));
  const finalInvoiceNo = isAutoGenerated ? generatedInvoiceNo : (saleData.invoiceNo || generatedInvoiceNo);

  const newSale = {
    workspaceId: workspaceId || customer.workspaceId,
    companyId: companyId || customer.companyId,
    branchId: resolvedBranchId,
    customerId: customer._id,
    invoiceNo: finalInvoiceNo,
    date: saleData.date || new Date(),
    financialPeriodId,
    billingMode: saleData.billingMode || "B2C",
    subtotal: saleData.subtotal || 0,
    discount: saleData.discount || 0,
    tax: saleData.tax || 0,
    grandTotal: saleData.grandTotal || 0,
    cashTendered: saleData.cashTendered || 0,
    changeDue: saleData.changeDue || 0,
    paymentMethod: saleData.paymentMethod || "Cash",
    status: saleData.status || "Paid",
    items: Array.isArray(saleData.items) ? saleData.items : [],
    doctor: saleData.doctor || null,
    notes: saleData.notes || null,
    createdBy: user?._id || null,
    createdByName: user?.name || null,
    createdByEmail: user?.email || null,
  };

  const savedInvoice = await invoiceRepository.createInvoice(newSale);

  // Deduct inventory from Batch and ProductFacility
  if (Array.isArray(newSale.items) && newSale.items.length > 0) {
    for (const item of newSale.items) {
      const qtyToDeduct = Number(item.qty) || 0;
      if (qtyToDeduct <= 0) continue;

      const productId = item.productId || item.workspaceProductId || item.id;
      const rawBatchId = item.batchId || (item.batch && item.batch._id) || item.batch;

      if (rawBatchId) {
        try {
          const batchDoc = await Batch.findById(rawBatchId);
          if (batchDoc) {
            batchDoc.batchQty = Math.max(0, (batchDoc.batchQty || 0) - qtyToDeduct);

            await batchDoc.save();
          }
        } catch (err) {
          console.error("Error deducting batch stock for sale:", err);
        }
      }

      if (productId && resolvedBranchId) {
        try {
          const facilityDoc = await ProductFacility.findOne({
            product_id: productId,
            facility_id: resolvedBranchId
          });
          if (facilityDoc) {
            facilityDoc.total_qty_available = Math.max(0, (facilityDoc.total_qty_available || 0) - qtyToDeduct);
            facilityDoc.qoh = Math.max(0, (facilityDoc.qoh || 0) - qtyToDeduct);
            facilityDoc.atp = Math.max(0, (facilityDoc.atp || 0) - qtyToDeduct);
            await facilityDoc.save();
          }
        } catch (err) {
          console.error("Error deducting product facility stock for sale:", err);
        }
      }
    }
  }

  // Auto-create GSTR-1 Entry for GST Ledger
  try {
    const totalGst = Number(newSale.tax || saleData.tax || 0);
    const halfGst = totalGst / 2;
    const taxableAmt = Number(
      saleData.taxableAmount !== undefined
        ? saleData.taxableAmount
        : (newSale.subtotal || 0) - (newSale.discount || 0)
    );

    const company = await Company.findOne({ _id: newSale.companyId, workspaceId: newSale.workspaceId });
    const companyGstin = company?.gstin || "";
    const customerGstin = customer?.gstNumber || "";
    const isIgst = companyGstin && customerGstin && companyGstin.substring(0, 2) !== customerGstin.substring(0, 2);

    await gstLedgerRepository.createGstLedgerEntry({
      workspaceId: newSale.workspaceId,
      companyId: newSale.companyId,
      partyId: customer._id,
      voucherId: savedInvoice._id,
      voucherNumber: newSale.invoiceNo,
      voucherDate: newSale.date ? new Date(newSale.date) : new Date(),
      gstType: "GSTR-1",
      taxableAmount: taxableAmt,
      cgst: isIgst ? 0 : halfGst,
      sgst: isIgst ? 0 : halfGst,
      igst: isIgst ? totalGst : 0,
      totalAmount: Number(newSale.grandTotal || 0),
      narration: `Sale Bill ${newSale.invoiceNo} (${newSale.billingMode}) - Customer: ${customer.name || "Customer"}`,
    });
  } catch (gstErr) {
    console.error("Failed to auto-create GSTR-1 entry for sale bill:", gstErr);
  }

  // Auto-create Journal Vouchers for Sale and Payment
  try {
    const isCashPaid = (String(newSale.paymentMethod).toLowerCase() === "cash" || newSale.cashTendered > 0) && String(newSale.status).toLowerCase() === "paid" && newSale.grandTotal > 0;
    const isUpiPaid = String(newSale.paymentMethod).toLowerCase() === "upi" && String(newSale.status).toLowerCase() === "paid" && newSale.grandTotal > 0;
    

    
    // Find Sales Account
    const salesAccountsResult = await accountRepository.getAccounts(
      newSale.workspaceId,
      newSale.companyId,
      { accountCategory: "SALES" },
      { limit: 1 }
    );
    


    if (salesAccountsResult.accounts && salesAccountsResult.accounts.length > 0) {
      const salesAccount = salesAccountsResult.accounts[0];
      
      if (customer.ledgerAccountId) {
        // --- CUSTOMER HAS LEDGER ACCOUNT (2 JVs: Sale & Receipt) ---
        const saleJvPayload = {
          voucherDate: newSale.date,
          voucherType: "SALE",
          referenceNumber: newSale.invoiceNo,
          narration: `Sale against Invoice ${newSale.invoiceNo}`,
          status: "POSTED",
          lines: [
            {
              accountId: customer.ledgerAccountId,
              debit: newSale.grandTotal,
              credit: 0,
              narration: `Amount due for Invoice ${newSale.invoiceNo}`
            },
            {
              accountId: salesAccount._id,
              debit: 0,
              credit: newSale.grandTotal,
              narration: `Sales from Invoice ${newSale.invoiceNo}`
            }
          ]
        };
        
        console.log("--- ATTEMPTING TO CREATE SALES JV ---");
        console.log(JSON.stringify(saleJvPayload, null, 2));

        try {
          const jvResult = await journalVoucherService.createJournalVoucher(
            newSale.workspaceId,
            newSale.companyId,
            user?._id,
            saleJvPayload
          );
          console.log(`--- SALES JV CREATED SUCCESSFULLY: ${jvResult._id} ---`);
        } catch (jvErr) {
          console.error("--- FAILED TO CREATE SALES JV ---", jvErr);
        }

        if (isCashPaid) {
          const cashAccountsResult = await accountRepository.getAccounts(
            newSale.workspaceId,
            newSale.companyId,
            { accountCategory: "CASH" },
            { limit: 1 }
          );
          
          if (cashAccountsResult.accounts && cashAccountsResult.accounts.length > 0) {
            const cashLedgerAccount = cashAccountsResult.accounts[0];
            
            // Find the Treasury Cash Account linked to this ledger account
            const treasuryCashAccount = await CashAccount.findOne({ 
              ledgerAccountId: cashLedgerAccount._id, 
              companyId: newSale.companyId, 
              workspaceId: newSale.workspaceId,
              isDeleted: false 
            });

            if (treasuryCashAccount) {
              await cashTransactionService.createCashTransaction(
                newSale.workspaceId,
                newSale.companyId,
                user?._id,
                {
                  transactionDate: newSale.date || new Date(),
                  cashAccountId: treasuryCashAccount._id,
                  transactionType: "CASH_IN",
                  direction: "CREDIT",
                  amount: newSale.grandTotal,
                  referenceNumber: newSale.invoiceNo,
                  narration: `Cash Receipt for Invoice ${newSale.invoiceNo}`,
                  counterpartyAccountId: customer.ledgerAccountId,
                  denominations: [{ denomination: 1, quantity: newSale.grandTotal }],
                }
              );
            }
          }
        } else if (isUpiPaid) {
          // If paid via UPI, auto-generate Bank Transaction
          const primaryBankAccount = await BankAccount.findOne({
            companyId: newSale.companyId,
            workspaceId: newSale.workspaceId,
            isDeleted: false,
            isActive: true,
            isPrimary: true
          });

          // If no primary bank account, try finding any active bank account
          const bankAccount = primaryBankAccount || await BankAccount.findOne({
            companyId: newSale.companyId,
            workspaceId: newSale.workspaceId,
            isDeleted: false,
            isActive: true
          });

          if (bankAccount) {
            await bankTransactionService.createBankTransaction(
              newSale.workspaceId,
              newSale.companyId,
              user?._id,
              {
                transactionDate: newSale.date || new Date(),
                bankAccountId: bankAccount._id,
                transactionType: "UPI",
                direction: "CREDIT", // Money coming in
                amount: newSale.grandTotal,
                referenceNumber: newSale.invoiceNo,
                narration: `UPI Receipt for Invoice ${newSale.invoiceNo}`,
                counterpartyAccountId: customer.ledgerAccountId
              }
            );
          }
        }
      } else if (isCashPaid) {
        // --- CUSTOMER HAS NO LEDGER ACCOUNT, BUT IT IS A CASH SALE (1 JV via Cash Transaction: Direct Cash -> Sales) ---
        const cashAccountsResult = await accountRepository.getAccounts(
          newSale.workspaceId,
          newSale.companyId,
          { accountCategory: "CASH" },
          { limit: 1 }
        );
        
        if (cashAccountsResult.accounts && cashAccountsResult.accounts.length > 0) {
          const cashLedgerAccount = cashAccountsResult.accounts[0];
          
          // Find the Treasury Cash Account linked to this ledger account
          const treasuryCashAccount = await CashAccount.findOne({ 
            ledgerAccountId: cashLedgerAccount._id, 
            companyId: newSale.companyId, 
            workspaceId: newSale.workspaceId,
            isDeleted: false 
          });

          if (treasuryCashAccount) {
            await cashTransactionService.createCashTransaction(
              newSale.workspaceId,
              newSale.companyId,
              user?._id,
              {
                transactionDate: newSale.date || new Date(),
                cashAccountId: treasuryCashAccount._id,
                transactionType: "CASH_IN",
                direction: "CREDIT",
                amount: newSale.grandTotal,
                referenceNumber: newSale.invoiceNo,
                narration: `Direct Cash Sale for Invoice ${newSale.invoiceNo}`,
                counterpartyAccountId: salesAccount._id,
                denominations: [{ denomination: 1, quantity: newSale.grandTotal }],
              }
            );
          }
        }

      } else if (isUpiPaid) {
        // --- CUSTOMER HAS NO LEDGER ACCOUNT, BUT IT IS A UPI SALE (1 JV via Bank Transaction: Direct Bank -> Sales) ---
        const primaryBankAccount = await BankAccount.findOne({
          companyId: newSale.companyId,
          workspaceId: newSale.workspaceId,
          isDeleted: false,
          isActive: true,
          isPrimary: true
        });

        const bankAccount = primaryBankAccount || await BankAccount.findOne({
          companyId: newSale.companyId,
          workspaceId: newSale.workspaceId,
          isDeleted: false,
          isActive: true
        });

        if (bankAccount) {
          await bankTransactionService.createBankTransaction(
            newSale.workspaceId,
            newSale.companyId,
            user?._id,
            {
              transactionDate: newSale.date || new Date(),
              bankAccountId: bankAccount._id,
              transactionType: "UPI",
              direction: "CREDIT",
              amount: newSale.grandTotal,
              referenceNumber: newSale.invoiceNo,
              narration: `Direct UPI Sale for Invoice ${newSale.invoiceNo}`,
              counterpartyAccountId: salesAccount._id
            }
          );
        }
      }
    }
  } catch (jvErr) {
    console.error("Error generating journal vouchers for sale bill:", jvErr);
  }

  return savedInvoice;
};

const getCustomerSales = async (customerId, companyId, workspaceId, branchId = null, pagination = {}) => {
  const customer = await customerRepository.findCustomerByIdCompanyAndWorkspace(
    customerId,
    companyId,
    workspaceId
  );

  if (!customer) {
    throw new ApiError(404, "Customer not found");
  }

  const result = await invoiceRepository.getInvoicesByCustomerId(
    customerId,
    companyId,
    workspaceId,
    { branchId },
    pagination
  );

  return {
    data: result.sales,
    meta: {
      total: result.total,
      page: result.page,
      limit: result.limit,
      totalSalesAmount: result.totalSalesAmount,
    },
  };
};

const getAllCustomerSales = async (companyId, workspaceId, branchId = null, pagination = {}) => {
  const result = await invoiceRepository.getAllInvoices(
    companyId,
    workspaceId,
    { branchId },
    pagination
  );

  return {
    data: result.sales,
    meta: {
      total: result.total,
      page: result.page,
      limit: result.limit,
    },
  };
};

export default {
  recordCustomerSale,
  getCustomerSales,
  getAllCustomerSales,
};
